package main

// OWMResponse Auto generated by https://mholt.github.io/json-to-go/
type OWMResponse struct {
	Coord struct {
		Lon float64 `json:"lon"`
		Lat float64 `json:"lat"`
	} `json:"coord"`
	Sys struct {
		Country string `json:"country"`
		Sunrise int    `json:"sunrise"`
		Sunset  int    `json:"sunset"`
	} `json:"sys"`
	Weather []struct {
		ID          int    `json:"id"`
		Main        string `json:"main"`
		Description string `json:"description"`
		Icon        string `json:"icon"`
	} `json:"weather"`
	Main struct {
		Temp     float64 `json:"temp"`
		Humidity int     `json:"humidity"`
		Pressure int     `json:"pressure"`
		TempMin  float64 `json:"temp_min"`
		TempMax  float64 `json:"temp_max"`
	} `json:"main"`
	Wind struct {
		Speed float64 `json:"speed"`
		Deg   float64 `json:"deg"`
	} `json:"wind"`
	Rain struct {
		ThreeH int `json:"3h"`
	} `json:"rain"`
	Clouds struct {
		All int `json:"all"`
	} `json:"clouds"`
	Dt   int    `json:"dt"`
	ID   int    `json:"id"`
	Name string `json:"name"`
	Cod  int    `json:"cod"`
}

// WeatherMap weatherIDと日本語の天気およびSlack絵文字との対応
var WeatherMap = map[int]weatherCondition {
	200: weatherCondition {"雷雨(小雨)", ":thunder_cloud_and_rain:"},
	201: weatherCondition {"雷雨(雨)", ":thunder_cloud_and_rain:"},
	202: weatherCondition {"雷雨(大雨)", ":thunder_cloud_and_rain:"},
	210: weatherCondition {"弱い雷雨", ":thunder_cloud_and_rain:"},
	211: weatherCondition {"雷雨", ":thunder_cloud_and_rain:"},
	212: weatherCondition {"激しい雷雨", ":thunder_cloud_and_rain:"},
	221: weatherCondition {"不規則な雷雨", ":thunder_cloud_and_rain:"},
	230: weatherCondition {"雷雨(薄い霧雨)", ":thunder_cloud_and_rain:"},
	231: weatherCondition {"雷雨(霧雨)", ":thunder_cloud_and_rain:"},
	232: weatherCondition {"雷雨(濃い霧雨)", ":thunder_cloud_and_rain:"},

	300: weatherCondition {"薄い霧", ":fog:"},
	301: weatherCondition {"霧", ":fog:"},
	302: weatherCondition {"濃い霧", ":fog:"},
	310: weatherCondition {"薄い霧雨", ":fog:"},
	311: weatherCondition {"霧雨", ":fog:"},
	312: weatherCondition {"濃い霧雨", ":fog:"},
	313: weatherCondition {"にわか雨と霧", ":rain_cloud:"},
	314: weatherCondition {"激しいにわか雨と霧", ":rain_cloud:"},
	321: weatherCondition {"にわか霧", ":fog:"},

	500: weatherCondition {"小雨", ":closed_umbrella:"},
	501: weatherCondition {"並雨", ":umbrella:"},
	502: weatherCondition {"激しい雨", ":umbrella_with_rain_drops:"},
	503: weatherCondition {"とても激しい雨", ":umbrella_with_rain_drops:"},
	504: weatherCondition {"とてつもなく激しい雨", ":umbrella_with_rain_drops:"},
	511: weatherCondition {"非常に冷たい雨", ":umbrella_with_rain_drops:"},
	520: weatherCondition {"軽いにわか雨", ":umbrella:"},
	521: weatherCondition {"にわか雨", ":umbrella:"},
	522: weatherCondition {"激しいにわか雨", ":umbrella_with_rain_drops:"},
	531: weatherCondition {"不規則なにわか雨", ":umbrella:"},

	600: weatherCondition {"小雪", ":snow_cloud:"},
	601: weatherCondition {"雪", ":snowman_without_snow:"},
	602: weatherCondition {"大雪", ":snowman:"},
	611: weatherCondition {"みぞれ", ":snow_cloud:"},
	612: weatherCondition {"軽いにわかみぞれ", ":snow_cloud:"},
	613: weatherCondition {"にわかみぞれ", ":snow_cloud:"},
	615: weatherCondition {"小雨時々雪", ":snow_cloud:"},
	616: weatherCondition {"雨時々雪", ":snow_cloud:"},
	620: weatherCondition {"にわか小雪", ":snow_cloud:"},
	621: weatherCondition {"にわか雪", ":snowman_without_snow:"},
	622: weatherCondition {"激しいにわか雪", ":snowman:"},

	701: weatherCondition {"もや", ":fog:"},
	711: weatherCondition {"煙たい(大気汚染)", ":mask:"},
	721: weatherCondition {"かすみ", ":fog:"},
	731: weatherCondition {"砂塵扇風", ":tornado:"},
	741: weatherCondition {"霧", ":fog:"},
	751: weatherCondition {"黄砂", ":camel:"},
	761: weatherCondition {"塵", ":fog:"},
	762: weatherCondition {"火山灰", ":volcano:"},
	771: weatherCondition {"スコール", ":umbrella_with_rain_drops:"},
	781: weatherCondition {"竜巻", ":tornado:"},

	800: weatherCondition {"快晴", ":sunny:"},

	801: weatherCondition {"ほとんど雲がない", ":mostly_sunny:"},
	802: weatherCondition {"ちぎれ雲(少)", ":partly_sunny:"},
	803: weatherCondition {"ちぎれ雲(多)", ":barely_sunny:"},
	804: weatherCondition {"曇り空", ":cloud:"},
}
